const APP_CONFIG = 'APP_CONFIG';
const PRODUCT = 'PRODUCT';
const PRODUCT_OPTION = 'PRODUCT_OPTION';
const PRODUCT_OPTION_LIST = 'PRODUCT_OPTION_LSIT';

export {
    APP_CONFIG,
    PRODUCT,
    PRODUCT_OPTION,
    PRODUCT_OPTION_LIST,
}