const APP_CONFIG = 'APP_CONFIG';
const PRODUCT = 'PRODUCT';
const TRANSACTION = 'TRANSACTION';
const TRANSACTION_ITEMS = 'TRANSACTION_ITEMS';
const ORDER = 'ORDER';
const ORDER_ITEMS = 'ORDER_ITEMS';
const NEW_ORDER = 'NEW_ORDER';
const NEW_ORDER_ITEMS = 'NEW_ORDER_ITEMS';
const PRODUCT_OPTION = 'PRODUCT_OPTION';
const PRODUCT_OPTION_LIST = 'PRODUCT_OPTION_LSIT';

export {
    APP_CONFIG,
    PRODUCT,
    TRANSACTION,
    TRANSACTION_ITEMS,
    ORDER,
    ORDER_ITEMS,
    NEW_ORDER,
    NEW_ORDER_ITEMS,
    PRODUCT_OPTION,
    PRODUCT_OPTION_LIST,
}